- hosts: localhost
  gather_facts: False
  vars:
    vpcname: My VPC
    vpc_cidr_block: "10.0.0.0/16"
    vpc_public_subnet_cidr: "10.0.0.0/24"
    keyname: ansible-key

  tasks:
    - name: Include secret
      include_vars: secret.yml
       
    - name: Provision a set of instances
      ec2:
         aws_access_key: "{{ ec2_access_key }}"
         aws_secret_key: "{{ ec2_secret_key }}"
         region: "{{ region }}"
         group_id: "{{ group_id }}"
         vpc_subnet_id: "{{ subnet_id }}"
         key_name: "{{ keyname }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         exact_count: "{{ count }}"
         count_tag:
            Name: "{{ tag }}"
         instance_tags:
            Name: "{{ tag }}"
         assign_public_ip: yes
      register: ec2

    - name: Create EBS volume and attach to instances
      ec2_vol:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        instance: "{{ item }}"
        volume_size: "{{ volume_size }}"
        device_name: /dev/xvdf
        delete_on_termination: yes
      with_items: "{{ ec2.instance_ids }}"
      register: ec2_vol

    - name: Print ec2.instances
      debug:
        msg: "ip = {{ item.public_ip }}"
      with_items:
        - "{{ ec2.instances }}"
    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items:
        - "{{ ec2.instances }}"
